# Generated by Django 3.2.9 on 2021-11-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='icon name'),
        ),
    ]
