# Generated by Django 3.2.9 on 2021-11-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True, max_length=524288, verbose_name='content'),
        ),
    ]
