# Generated by Django 3.2.9 on 2021-11-08 17:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20211108_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='update time'),
        ),
    ]
