# Generated by Django 3.2.9 on 2022-05-22 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0005_alter_note_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('note_id', models.UUIDField(verbose_name='note id')),
                ('deleted_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='deletion time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Deletion',
                'verbose_name_plural': 'Deletions',
            },
        ),
    ]
