# Generated by Django 3.2.9 on 2022-05-23 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_deletion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deletion',
            old_name='note_id',
            new_name='note_static_id',
        ),
        migrations.AddField(
            model_name='deletion',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notes.note', verbose_name='note'),
        ),
    ]
