# Generated by Django 3.2.9 on 2022-05-23 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_auto_20220523_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletion',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletions', to='notes.note', verbose_name='note'),
        ),
    ]
