# Generated by Django 3.2.9 on 2022-05-23 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_alter_deletion_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletion',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='deletion creation time'),
        ),
    ]
