# Generated by Django 3.2.9 on 2022-05-24 13:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_deletion_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deletion',
            options={'ordering': ('deleted_at', 'created_at'), 'verbose_name': 'Deletion', 'verbose_name_plural': 'Deletions'},
        ),
        migrations.AddField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='creation time'),
        ),
    ]
