# Generated by Django 3.2.9 on 2021-11-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lang',
            field=models.CharField(default='en-us', max_length=10, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='user',
            name='max_data_size',
            field=models.IntegerField(default=1048576, verbose_name='allowed data size'),
        ),
        migrations.AddField(
            model_name='user',
            name='used_data_size',
            field=models.IntegerField(default=0, verbose_name='used data size'),
            preserve_default=False,
        ),
    ]
