# Generated by Django 3.2.9 on 2021-11-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211107_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='used_data_size',
            field=models.IntegerField(default=0, verbose_name='used data size'),
        ),
    ]
